### ISSUE TITLE
pycsw install seems to be missing

### ISSUE THREAD

**Issue by smrazgs** [ngds/install-and-run#22]
http://ckanext-spatial.readthedocs.org/en/latest/csw.htmlhttp://ckanext-spatial.readthedocs.org/en/latest/csw.html

Or is the pycsw install buried somewhere?

the v1 installer from last May (https://github.com/ngds/install-and-run/archive/v1.zip) has shell script procedures for installing pycsw; not sure how this would translate to rpm

**Comment by ccaudill** [comment]
I got it set up on my local with the sample database from Adrian, seems all is working with no errors. Then I run the command "ckan-pycsw load”, which loads datasets from ckan api into csw database. Then I run “datastore-pycsw load”, which immediately deletes all records from csw database. 
Can you let me know whether this is the correct behavior, or, let me know the best way to verify that pycsw is set up correctly?
Thanks.
Fuhu

**Comment by ccaudill** [comment]
@FuhuXia 
We need to be sure that harvested data is actually using the USGIN standard, and that we're getting USGIN ISO metadata from a harvest. This was actually in the code here: https://github.com/ngds/ckanext-metadata where Adrian had said that he used Steve's custom federated standard for publish/harvest of metadata, but it needs testing. @smrazgs Can you confirm that this custom standard that you apparently provided Adrian with is the USGIN profile? If so, and the code from https://github.com/ngds/ckanext-metadata is being used, then we're likely good with USGIN ISO metadata being harvested in.

**Comment by ccaudill** [comment]
Pycsw has been integrated into RPM and can be demo’ed at uat server at http://uat-ngds.reisys.com.  I will publish the rpm once you confirm that everything is working as expected.
Thanks,
Fuhu

**Comment by ccaudill** [comment]
@FuhuXia 
I tried to harvest it in at http://demo.geothermaldata.org/harvest/test-rei-pycsw-test/job and it seems to have the same issue as before. It's not harvesting in. The message indicates that the job never starts.

**Comment by FuhuXia** [comment]
Job not starting indicates there is some problem with the harvester. Without shell access it is hard to debug. The easiest solution is to reboot the server. To harvest from uat server, make sure you use `http://uat-ngds.reisys.com/csw` as harvest source. Without `/csw` it is not valid source.

**Comment by ccaudill** [comment]
I see the same thing when testing at our live site, which we know harvests correctly. Any thoughts?
http://www.geothermaldata.org/harvest/test-rei-pycsw-test/job

**Comment by ccaudill** [comment]
@FuhuXia Can you please tell us where you are on this task?  Is there anything we can test for you?

**Comment by FuhuXia** [comment]
@ccaudill Please install the new version rpm on a fresh CentOS 6.6 box, then test pycsw harvesting using our UAT as source. The instruction should be same as described in the **Deployment on Your Own Server** part of [readme file](https://github.com/ngds/install-and-run/blob/master/README.md). I updated it with a few steps to change the external url in files `/etc/ckan/production.ini` and `/var/lib/tomcat6/webapps/geoserver/data/global.xml`.

**Comment by ccaudill** [comment]
Excellent, will do. Thanks @FuhuXia

**Comment by ccaudill** [comment]
@FuhuXia  @smrazgs 
I'm having some issues in harvesting in the new build CSW, and am still unable to get it to harvest into another instance.
We have 2 servers with the new rpm, running CentOS6.6. The 'GINstack' test server has successfully harvested in something: http://159.87.39.4/harvest/admin/michigan-geological-survey-ngds-node
But when I try to harvest from that server to another instance, the 'production' server, I cannot get records harvested from the previously listed server: http://159.87.39.5/harvest/azgs-ginstack-test-harvest/job
It says it's started, but not finished. It harvests in no records.
The CSW GetCapabilites request is responding from the installation I'm trying to harvest: http://159.87.39.4/csw?request=GetCapabilities&Service=CSW&Version=2.0.2

**Comment by ccaudill** [comment]
I also tried harvesting in from the REI UAT: http://159.87.39.5/harvest/test-rei-pycsw-test 
It hasn't finished yet, but doesn't seem to be harvesting in either.

**Comment by FuhuXia** [comment]
http://159.87.39.4/ looks fine to me. Can you modify the file /etc/cron.d/ckan-pycsw and delete everything after && so it reads: 
`0 1 * * * root /usr/lib/ckan/bin/paster --plugin=ckanext-spatial ckan-pycsw load -p /etc/ckan/pycsw.cfg >> /var/log/ckan-pycsw-loader.log 2>&1`
This way we can get the csw into db. Without it the csw db will remain empty because second command delete everything.

For http://159.87.39.5, please post the last 50 lines for /var/log/harvester_run.log, /var/log/gather-consumer.log, /var/log/fetch-consumer.log, so I can see what is with the harvester.

**Comment by ccaudill** [comment]
@FuhuXia  Here are the last 50 lines from the harvester log -

2015-02-06 10:15:37,305 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-02-06 10:15:37,308 DEBUG [ckanext.harvest.model] Harvest tables already exist
2015-02-06 10:15:37,363 INFO  [ckanext.harvest.logic.action.update] Harvest job run: {}
2015-02-06 10:15:37,399 INFO  [ckanext.harvest.logic.action.update] No new harvest jobs.

Traceback (most recent call last):
  File "/usr/bin/ckan", line 59, in <module>
    load_entry_point('PasteScript', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 122, in command
    self.run_harvester()
  File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 287, in run_harvester
    jobs = get_action('harvest_jobs_run')(context,{})
  File "/usr/lib/ckan/src/ckan/ckan/logic/__init__.py", line 419, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/logic/action/update.py", line 338, in harvest_jobs_run
    raise Exception('There are no new harvesting jobs')
Exception: There are no new harvesting jobs
2015-02-06 10:30:17,203 INFO  [ckanext.facets.helpers] Metadata plugin custom facets loaded
2015-02-06 10:30:17,208 DEBUG [ckanext.ngds.sysadmin.model.db] Sysadmin configuration table already exists
2015-02-06 10:30:20,475 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2015-02-06 10:30:20,494 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2015-02-06 10:30:20,510 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-02-06 10:30:20,513 DEBUG [ckanext.harvest.model] Harvest tables already exist
2015-02-06 10:30:20,566 INFO  [ckanext.harvest.logic.action.update] Harvest job run: {}
2015-02-06 10:30:20,602 INFO  [ckanext.harvest.logic.action.update] No new harvest jobs.

Traceback (most recent call last):
  File "/usr/bin/ckan", line 59, in <module>
    load_entry_point('PasteScript', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 122, in command
    self.run_harvester()
  File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 287, in run_harvester
    jobs = get_action('harvest_jobs_run')(context,{})
  File "/usr/lib/ckan/src/ckan/ckan/logic/__init__.py", line 419, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/logic/action/update.py", line 338, in harvest_jobs_run
    raise Exception('There are no new harvesting jobs')
Exception: There are no new harvesting jobs

**Comment by ccaudill** [comment]
@FuhuXia I can modify the file /etc/cron.d/ckan-pycsw but I don't understand why that needs to be done. Could you explain? Thank you

**Comment by ccaudill** [comment]
@FuhuXia Here are the last 50 lines from the gather-consumer log:

[root@localhost log]# 2015-02-06 10:15:37,305 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-02-06 10:15:37,308 DEBUG [ckanext.harvest.model] Harvest tables already exist
-bash: 2015-02-06: command not found
2015-02-06 10:15:37,363 INFO  [ckanext.harvest.logic.action.update] Harvest job run: {}
2015-02-06 10:15:37,399 INFO  [ckanext.harvest.logic.action.update] No new harvest jobs.
[root@localhost log]# 2015-02-06 10:15:37,308 DEBUG [ckanext.harvest.model] Harvest tables already exist
  File "/usr/bin/ckan", line 59, in <module>
    load_entry_point('PasteScript', 'console_scripts', 'paster')()
-bash: 2015-02-06: command not found
  File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 104, in run
[root@localhost log]# 2015-02-06 10:15:37,363 INFO  [ckanext.harvest.logic.action.update] Harvest job run: {}
  File "/usr/lib/ckan/src/ckan/ckan/logic/__init__.py", line 419, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/logic/action/update.py", line 338, in harvest_jobs_run
-bash: 2015-02-06: command not found
    raise Exception('There are no new harvesting jobs')
[root@localhost log]# 2015-02-06 10:15:37,399 INFO  [ckanext.harvest.logic.action.update] No new harvest jobs.
2015-02-06 10:30:20,475 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2015-02-06 10:30:20,494 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2015-02-06 10:30:20,510 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-02-06 10:30:20,513 DEBUG [ckanext.harvest.model] Harvest tables already exist
2015-02-06 10:30:20,566 INFO  [ckanext.harvest.logic.action.update] Harvest job run: {}
2015-02-06 10:30:20,602 INFO  [ckanext.harvest.logic.action.update] No new harvest jobs.
-bash: 2015-02-06: command not found

[root@localhost log]#
[root@localhost log]# Traceback (most recent call last):
-bash: syntax error near unexpected token `most'
[root@localhost log]#   File "/usr/bin/ckan", line 59, in <module>
-bash: syntax error near unexpected token `newline'
[root@localhost log]#     load_entry_point('PasteScript', 'console_scripts', 'paster')()
-bash: syntax error near unexpected token `'PasteScript','
[root@localhost log]#   File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 104, in run
    result = _action(context, data_dict, **kw)
-bash: File: command not found
  File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/logic/action/update.py", line 338, in harvest_jobs_run
[root@localhost log]#     invoke(command, command_name, options, args[1:])
-bash: syntax error near unexpected token `command,'
[root@localhost log]#   File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 143, in invoke
-bash: File: command not found
[root@localhost log]#     exit_code = runner.run(args)
-bash: syntax error near unexpected token `('
[root@localhost log]#   File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 238, in run
-bash: File: command not found
[root@localhost log]#     result = self.command()
-bash: syntax error near unexpected token `('
[root@localhost log]#   File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 122, in command
-bash: File: command not found
[root@localhost log]#     self.run_harvester()
>   File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 287, in run_harvester
-bash: syntax error near unexpected token `File'
[root@localhost log]#     jobs = get_action('harvest_jobs_run')(context,{})
-bash: syntax error near unexpected token `('
[root@localhost log]#   File "/usr/lib/ckan/src/ckan/ckan/logic/__init__.py", line 419, in wrapped
-bash: File: command not found
[root@localhost log]#     result = _action(context, data_dict, **kw)
-bash: syntax error near unexpected token `('
[root@localhost log]#   File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/logic/action/update.py", line 338, in harvest_jobs_run
-bash: File: command not found
[root@localhost log]#     raise Exception('There are no new harvesting jobs')
-bash: syntax error near unexpected token `('
[root@localhost log]# Exception: There are no new harvesting jobs
-bash: Exception:: command not found
[root@localhost log]# 2015-02-06 10:30:17,203 INFO  [ckanext.facets.helpers] Metadata plugin custom facets loaded
-bash: 2015-02-06: command not found
[root@localhost log]# 2015-02-06 10:30:17,208 DEBUG [ckanext.ngds.sysadmin.model.db] Sysadmin configuration table already exists
-bash: 2015-02-06: command not found
[root@localhost log]# 2015-02-06 10:30:20,475 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
-bash: 2015-02-06: command not found
[root@localhost log]# 2015-02-06 10:30:20,494 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
-bash: 2015-02-06: command not found
[root@localhost log]# 2015-02-06 10:30:20,510 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
-bash: 2015-02-06: command not found
[root@localhost log]# 2015-02-06 10:30:20,513 DEBUG [ckanext.harvest.model] Harvest tables already exist
-bash: 2015-02-06: command not found
[root@localhost log]# 2015-02-06 10:30:20,566 INFO  [ckanext.harvest.logic.action.update] Harvest job run: {}
-bash: 2015-02-06: command not found
[root@localhost log]# 2015-02-06 10:30:20,602 INFO  [ckanext.harvest.logic.action.update] No new harvest jobs.
-bash: 2015-02-06: command not found
[root@localhost log]#
[root@localhost log]# Traceback (most recent call last):
-bash: syntax error near unexpected token `most'
[root@localhost log]#   File "/usr/bin/ckan", line 59, in <module>
-bash: syntax error near unexpected token `newline'
[root@localhost log]#     load_entry_point('PasteScript', 'console_scripts', 'paster')()
-bash: syntax error near unexpected token `'PasteScript','
[root@localhost log]#   File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 104, in run
-bash: File: command not found
[root@localhost log]#     invoke(command, command_name, options, args[1:])
-bash: syntax error near unexpected token `command,'
[root@localhost log]#   File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 143, in invoke
-bash: File: command not found
[root@localhost log]#     exit_code = runner.run(args)
-bash: syntax error near unexpected token `('
[root@localhost log]#   File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 238, in run
-bash: File: command not found
[root@localhost log]#     result = self.command()
-bash: syntax error near unexpected token `('
[root@localhost log]#   File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 122, in command
-bash: File: command not found
[root@localhost log]#     self.run_harvester()
>   File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 287, in run_harvester
-bash: syntax error near unexpected token `File'
[root@localhost log]#     jobs = get_action('harvest_jobs_run')(context,{})
-bash: syntax error near unexpected token `('
[root@localhost log]#   File "/usr/lib/ckan/src/ckan/ckan/logic/__init__.py", line 419, in wrapped
-bash: File: command not found
[root@localhost log]#     result = _action(context, data_dict, **kw)
-bash: syntax error near unexpected token `('
[root@localhost log]#   File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/logic/action/update.py", line 338, in harvest_jobs_run
-bash: File: command not found
[root@localhost log]#     raise Exception('There are no new harvesting jobs')
-bash: syntax error near unexpected token `('
[root@localhost log]# Exception: There are no new harvesting jobs
-bash: Exception:: command not found
[root@localhost log]# ^C
[root@localhost log]# tail -n 50 gather-consumer.log
2015-02-05 15:34:45,079 INFO  [ckanext.facets.helpers] Metadata plugin custom facets loaded
2015-02-05 15:34:45,092 DEBUG [ckanext.ngds.sysadmin.model.db] Sysadmin configuration table already exists
2015-02-05 15:34:48,839 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2015-02-05 15:34:48,881 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2015-02-05 15:34:48,899 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-02-05 15:34:48,906 DEBUG [ckanext.harvest.model] Harvest tables already exist
2015-02-05 15:34:49,029 DEBUG [ckanext.harvest.queue] Gather queue consumer registered
2015-02-05 20:30:22,947 DEBUG [ckanext.harvest.queue] Received harvest job id: 17fd913a-7b07-46e1-9654-8ee752cd6515
2015-02-05 20:30:22,966 DEBUG [ckanext.spatial.harvesters.csw.CSW.gather] CswHarvester gather_stage for job: <HarvestJob id=17fd913a-7b07-46e1-9654-8ee752cd6515 created=2015-02-06 03:22:55.371402 gather_started=2015-02-06 03:30:22.965920 gather_finished=None finished=None source_id=f6c8e2ba-1f78-4cf2-aad5-8c51668cb068 status=Running>
2015-02-05 20:30:26,080 ERROR [ckanext.harvest.harvesters.base] Error contacting the CSW server: <urlopen error [Errno 113] No route to host>
2015-02-05 20:30:26,088 ERROR [ckanext.harvest.queue] Gather stage failed
2015-02-05 20:45:21,650 DEBUG [ckanext.harvest.queue] Received harvest job id: ec1661ea-a6da-4b28-9400-f30171877c1a
2015-02-05 20:45:21,663 DEBUG [ckanext.spatial.harvesters.csw.CSW.gather] CswHarvester gather_stage for job: <HarvestJob id=ec1661ea-a6da-4b28-9400-f30171877c1a created=2015-02-06 03:41:15.012250 gather_started=2015-02-06 03:45:21.663245 gather_finished=None finished=None source_id=f6c8e2ba-1f78-4cf2-aad5-8c51668cb068 status=Running>
2015-02-05 20:45:24,684 ERROR [ckanext.harvest.harvesters.base] Error contacting the CSW server: <urlopen error [Errno 113] No route to host>
2015-02-05 20:45:24,690 ERROR [ckanext.harvest.queue] Gather stage failed
2015-02-05 21:15:22,766 DEBUG [ckanext.harvest.queue] Received harvest job id: 1bc05784-4c21-4a09-8779-e3e919eebf13
2015-02-05 21:15:22,780 DEBUG [ckanext.spatial.harvesters.csw.CSW.gather] CswHarvester gather_stage for job: <HarvestJob id=1bc05784-4c21-4a09-8779-e3e919eebf13 created=2015-02-06 04:07:33.343631 gather_started=2015-02-06 04:15:22.780019 gather_finished=None finished=None source_id=33a553f8-354d-4b17-b1d6-3d95c006aabf status=Running>
2015-02-05 21:15:33,082 ERROR [ckanext.harvest.harvesters.base] Error contacting the CSW server: <urlopen error timed out>
2015-02-05 21:15:33,088 ERROR [ckanext.harvest.queue] Gather stage failed
2015-02-05 21:15:33,089 DEBUG [ckanext.harvest.queue] Received harvest job id: 8cf57ace-2571-4385-aeb5-c9157e6ba4e4
2015-02-05 21:15:33,094 DEBUG [ckanext.spatial.harvesters.csw.CSW.gather] CswHarvester gather_stage for job: <HarvestJob id=8cf57ace-2571-4385-aeb5-c9157e6ba4e4 created=2015-02-06 04:07:01.153399 gather_started=2015-02-06 04:15:33.094168 gather_finished=None finished=None source_id=f6c8e2ba-1f78-4cf2-aad5-8c51668cb068 status=Running>
2015-02-05 21:15:36,113 ERROR [ckanext.harvest.harvesters.base] Error contacting the CSW server: <urlopen error [Errno 113] No route to host>
2015-02-05 21:15:36,116 ERROR [ckanext.harvest.queue] Gather stage failed

**Comment by ccaudill** [comment]
@FuhuXia and the fetch-consumer:

[root@localhost log]# tail -n 50 fetch-consumer.log
2015-02-05 15:34:30,580 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2015-02-05 15:34:30,619 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2015-02-05 15:34:30,639 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-02-05 15:34:30,646 DEBUG [ckanext.harvest.model] Harvest tables already exist
2015-02-05 15:34:30,899 DEBUG [ckanext.harvest.queue] Fetch queue consumer registered
2015-02-05 15:34:31,088 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2015-02-05 15:34:31,134 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2015-02-05 15:34:31,157 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-02-05 15:34:31,163 DEBUG [ckanext.harvest.model] Harvest tables already exist
2015-02-05 15:34:31,285 DEBUG [ckanext.harvest.queue] Fetch queue consumer registered
2015-02-05 15:34:32,123 INFO  [ckanext.facets.helpers] Metadata plugin custom facets loaded
2015-02-05 15:34:32,139 DEBUG [ckanext.ngds.sysadmin.model.db] Sysadmin configuration table already exists
2015-02-05 15:34:36,909 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2015-02-05 15:34:36,939 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2015-02-05 15:34:36,961 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-02-05 15:34:36,970 DEBUG [ckanext.harvest.model] Harvest tables already exist
2015-02-05 15:34:37,088 DEBUG [ckanext.harvest.queue] Fetch queue consumer registered
2015-02-05 15:34:39,886 INFO  [ckanext.facets.helpers] Metadata plugin custom facets loaded
2015-02-05 15:34:39,898 DEBUG [ckanext.ngds.sysadmin.model.db] Sysadmin configuration table already exists
2015-02-05 15:34:39,906 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2015-02-05 15:34:39,956 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2015-02-05 15:34:39,983 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-02-05 15:34:39,997 DEBUG [ckanext.harvest.model] Harvest tables already exist
2015-02-05 15:34:40,144 DEBUG [ckanext.harvest.queue] Fetch queue consumer registered
2015-02-05 15:34:41,628 INFO  [ckanext.facets.helpers] Metadata plugin custom facets loaded
2015-02-05 15:34:41,640 DEBUG [ckanext.ngds.sysadmin.model.db] Sysadmin configuration table already exists
2015-02-05 15:34:42,298 INFO  [ckanext.facets.helpers] Metadata plugin custom facets loaded
2015-02-05 15:34:42,310 DEBUG [ckanext.ngds.sysadmin.model.db] Sysadmin configuration table already exists
2015-02-05 15:34:44,296 INFO  [ckanext.facets.helpers] Metadata plugin custom facets loaded
2015-02-05 15:34:44,310 DEBUG [ckanext.ngds.sysadmin.model.db] Sysadmin configuration table already exists
2015-02-05 15:34:45,242 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2015-02-05 15:34:45,283 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2015-02-05 15:34:45,307 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-02-05 15:34:45,313 DEBUG [ckanext.harvest.model] Harvest tables already exist
2015-02-05 15:34:45,444 DEBUG [ckanext.harvest.queue] Fetch queue consumer registered
2015-02-05 15:34:46,444 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2015-02-05 15:34:46,499 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2015-02-05 15:34:46,525 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-02-05 15:34:46,547 DEBUG [ckanext.harvest.model] Harvest tables already exist
2015-02-05 15:34:46,710 DEBUG [ckanext.harvest.queue] Fetch queue consumer registered
2015-02-05 15:34:46,963 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2015-02-05 15:34:47,007 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2015-02-05 15:34:47,045 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-02-05 15:34:47,055 DEBUG [ckanext.harvest.model] Harvest tables already exist
2015-02-05 15:34:47,213 DEBUG [ckanext.harvest.queue] Fetch queue consumer registered
2015-02-05 15:34:48,316 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2015-02-05 15:34:48,415 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2015-02-05 15:34:48,481 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-02-05 15:34:48,501 DEBUG [ckanext.harvest.model] Harvest tables already exist
2015-02-05 15:34:48,758 DEBUG [ckanext.harvest.queue] Fetch queue consumer registered

**Comment by ccaudill** [comment]
@FuhuXia This doesn't seem to be a problem with the harvester, I suppose, because I am able to get a harvest from a source that's not a CKAN GINstack (rpm install).
http://159.87.39.5/harvest/test-usgin-catalog-harvest/job
I hope that helps...

**Comment by FuhuXia** [comment]
the reason for the /etc/cron.d/ckan-pycsw change is explained in my previous comment:
```
I got it set up on my local with the sample database from Adrian, 
seems all is working with no errors. Then I run the command "ckan-pycsw load”, 
which loads datasets from ckan api into csw database. Then I run “datastore-pycsw load”,
which immediately deletes all records from csw database. Can you let me know 
whether this is the correct behavior, or, let me know the best way to verify that
pycsw is set up correctly?
```
So let us stop the 2nd command "datastore-pycsw load" from running on 159.87.39.4 for now. The 1st command  `ckan-pycsw load` will add all harvested records into csw, then your 159.87.39.5 will be able to harvest from 159.87.39.4.

The reason for 159.87.39.5 not harvesting from our UAT, according to the log message **Error contacting the CSW server**, is that it cant connect to our uat server. Please run a ping on it to see what kind of networkk issue it is. Please show me the result for this command `ping uat-ngds.reisys.com`

**Comment by ccaudill** [comment]
[root@localhost ~]# ping uat-ngds.reisys.com
PING uat-ngds.reisys.com (65.242.96.26) 56(84) bytes of data.

**Comment by ccaudill** [comment]
@FuhuXia  Is there a way to get more granularity in the logs? For instance, looking at each http request to the server you're attempting to harvest from?

**Comment by FuhuXia** [comment]
The log is combined for all harvest jobs. But since you only have three sources, it is easy to put a watch on one harvest source. Here is what you can do:

1. Comment out the cron job in file /etc/cron.d/ckan-harvest. We will run it manually.

2. From web gui, make sure all other harvest jobs is not running. Then do a re-harvest (or clear and re-harvest) on the source you want to look at. 

3. Watch the logs realtime by these two commands:
tail -f /var/log/fetch-consumer.log &
tail -f /var/log/gather-consumer.log &

4. Manually run harvest job by this command:
ckan --plugin=ckanext-harvest harvester run -c /etc/ckan/production.ini

You can watch the progress shoing when harvest job is sent to gather stage, when it is sent to fetch stage, and when dataset being created. If there is error, it will show up in the log, from which you can tell which stage it fails.

**Comment by ccaudill** [comment]
If we are using a fresh install, why are we having these issues and you not?

**Comment by FuhuXia** [comment]
I did the same change on my uat server. If not, my csw will also be nearly empty. Records harvested from external source will be removed from csw db, only manually created datasets will stay in csw db.

**Comment by smrazgs** [comment]
So is the problem that Christy is harvesting records into CKAN, but they're not sticking in the CSW database, only going into the CKAN dataStore?  I thought Adrian had fixed that problem so that harvested records would be visible for harvesting out. Did that get lost?

**Comment by ccaudill** [comment]
@FuhuXia  I edited the etc/cron.d/ckan-pycsw  on 159.87.39.4 and then tried harvesting back into 159.87.39.5 with same results as previous: http://159.87.39.5/harvest/admin/azgs-ginstack-test-harvest

**Comment by FuhuXia** [comment]
@smrazgs That is right. The current ckanext-datastorecsw code will delete most csw records, if not all.

@ccaudill The csw cron jon will start at 1am. You can manually run it via this command:
`/usr/lib/ckan/bin/paster --plugin=ckanext-spatial ckan-pycsw load -p /etc/ckan/pycsw.cfg`, after done, try reharvest from 159.87.39.5.

**Comment by ccaudill** [comment]
@FuhuXia Okay, will do - thanks!

It sounds like we the correct thing is to ensure that the records are available for harvest, correct?

**Comment by smrazgs** [comment]
@asonnenschein -- didn't you fix the harvester so the harvested-in records are accessible to pyCSW to be harvested out?

**Comment by ccaudill** [comment]
I was able to successfully harvest from the REI UAT: http://159.87.39.5/harvest/admin/test-rei-pycsw-test but not ours at 159.87.39.4  - I think we've narrowed down what's going on here though.

**Comment by ccaudill** [comment]
As a side note, we are very anxious to get this and https://github.com/ngds/ckanext-geoserver/issues/7 resolved; here is a note from one of our partners who installed the GINstack:
"How is the node-in-a-box bug removal going? We have some upcoming deliveries to make for our play-fairway grant coming up and it would be good to know the status so that we can plan work-arounds"

**Comment by asonnenschein** [comment]
@smrazgs What you're describing should be the default behavior of the CKAN harvester; there shouldn't have been anything to fix.  Harvested in data gets inserted into the PyCSW DB via execution of a command line tool that should be running regularly in a CRON job.

@FuhuXia What exactly got lost?  (Ckanext-datastorecsw)[https://github.com/ngds/ckanext-datastorecsw#command-line-interface] hasn't been altered since June.  The correct way to set it up would be just like the stock harvester - run `paster datastore-pycsw load -p src/ckan/pycsw.cfg -u http://ckan.instance.org` in it's own CRON job.

(Here)[https://github.com/ngds/ckanext-datastorecsw/blob/e753a13e6d13d5364d504d22d6e785a4da6bb516/bin/datastore_pycsw.py#L49] is the only place in the entire codebase that sqlalchemy's `delete` command is being called.

**Comment by FuhuXia** [comment]
I am running the two load commands (`ckan-pycsw load` and  `datastore-pycsw load`) side by side in https://github.com/ngds/install-and-run/blob/master/rpm_install/etc/cron.d/ckan-pycsw#L2

The default behavior of csw load command is to add/update/delete csw datasets and make it consistent with ckan db per **its own query**. If the queries are different in the two loads commands, we can expect that they are going to delete each other's datasets. And that is what we observed: `ckan-pycsw load` added harvested datasets into csw, but following `datastore-pycsw load` will delete them right away.

**Comment by smrazgs** [comment]
Why are both load commands getting run? Doesn't datastore-pycsw synchronize the pycsw db with the datastore db?

**Comment by FuhuXia** [comment]
Both commands are in the original upstart script, therefore they both go to cron jobs. If only one is supposed to run, I guess it is `datastore-pycsw load`. I can do this in UAT server, then out of the 9000+ datasets, only a handful of them will go to csw database. Please confirm this is expected behavior.

**Comment by ccaudill** [comment]
Notes from 20150210 meeting: everything needs to go into CSW (harvested and published), so he'll modify the second cron job. We're on the same page now. - We'll make those modifications now.

**Comment by FuhuXia** [comment]
this is fixed in https://github.com/REI-Systems/ckanext-datastorecsw/commit/016ec77163dfc84a024302db09fa545be81746bf. a new rpm is in process to include this change.

**Comment by ccaudill** [comment]
Excellent!  Please let us know when we can update our install. Thanks

**Comment by FuhuXia** [comment]
rpm version 306 is ready. you can update existing instance with command `yum clean metadata && yum update ngds.ckan`

**Comment by ccaudill** [comment]
I've updated and restarted apache on both of our test machines. I get the exact same result when attmepting to harvest from one into another - no records. Still getting the error " 	Error contacting the CSW server: <urlopen error [Errno 113] No route to host>"
@FuhuXia

**Comment by FuhuXia** [comment]
the issue you are having is network issue. one of your server cant reach the other. do a ping request on the command line to confirm the issue.

**Comment by ccaudill** [comment]
Thanks @FuhuXia I'm looking into that problem now and then I'll retry the harvests and let you know.

**Comment by ccaudill** [comment]
@FuhuXia We figured out that due to state ports, I needed to use the internal IP address http://10.208.3.122/csw. Now the error message changed to:
No records received from the CSW server
When there are 38. Any thoughts?

**Comment by ccaudill** [comment]
we had a new node test the update rpm using:
yum clean metadata && yum update ngds.ckan
Now, when I hit http://mbmggin.mtech.edu/csw  or 
http://mbmggin.mtech.edu/csw?request=GetCapabilities&Service=CSW&Version=2.0.2
I get the error message "Could not load repository (local): (OperationalError) FATAL:  database "pycsw" does not exist
 None None"
Thoughts??

**Comment by FuhuXia** [comment]
the rpm update path wont do any database change. the pycsw db was introduced in last two or three rpm version. So, if you are updating from an older version, you will need to manually add pycsw db.
```
sudo -u postgres createdb -O ckan_default pycsw -E utf-8

sudo -u postgres psql -d pycsw -f /usr/pgsql-9.1/share/contrib/postgis-1.5/postgis.sql > /dev/null

sudo -u postgres psql -d pycsw -f /usr/pgsql-9.1/share/contrib/postgis-1.5/spatial_ref_sys.sql > /dev/null

sudo -u postgres psql -d pycsw -c 'GRANT SELECT, UPDATE, INSERT, DELETE ON spatial_ref_sys TO ckan_default' > /dev/null

sudo -u postgres psql -d pycsw -c 'GRANT SELECT, UPDATE, INSERT, DELETE ON geometry_columns TO ckan_default' > /dev/null

cd /usr/lib/ckan/src/ckanext-spatial

../../bin/paster --plugin=ckanext-spatial ckan-pycsw setup -p /etc/ckan/pycsw.cfg
```

**Comment by ccaudill** [comment]
thanks - this is really important as all of our new nodes installed late last year and are waiting for these updates.

**Comment by ccaudill** [comment]
From the user:
"when I try to run cmd#1  (in the postgis-1.5 directory) now get 
Created: database creation failed: ERROR:  database "pycsw" already exists"

And from http://mbmggin.mtech.edu/csw I now see:
"<ows:ExceptionText>Could not load repository (local): records</ows:ExceptionText>"

**Comment by ccaudill** [comment]
@FuhuXia Could you give us some direction on what needs to be done with this install?  I believe someone was going to updated the ReadMe https://github.com/ngds/install-and-run to include information on what users needed to do who installed in the Nov timeframe of last year? Here's what this node provider said. "We actually installed mid-late November when it first came out I thought. It said updating for .203 to .306"

**Comment by FuhuXia** [comment]
Readme file updated. Instruction for updating from rpm prior to 300 has been added.

**Comment by ccaudill** [comment]
@lukejbuckley https://github.com/ngds/install-and-run#updating-ngds Looks like pretty great instructions (if a lot of manual work). If you have the time, it would be great if you could do this update so we can continue testing. Thanks for your support!

**Comment by ccaudill** [comment]
@FuhuXia Thank you.  Might there be a way around the user having to do anything with the production.ini file?

**Comment by FuhuXia** [comment]
One parameter in production.ini is related the external url. Its value is unique to each and every instance, in order to make the datapusher and geoserver preview works. It has to be set manually. Hopefully the user has to do it only once... until next time we change some config in production.ini, which does not happen often unless we are introducing some new extensions/plugins.

**Comment by lukejbuckley** [comment]
To be clear…

I need to

1.       replace production.ini with production.ini.rpmnew

2.       then edit production.ini to fix the ckan.hostname

3.       fix proxyBaseUrl in global.xml

Luke Buckley | Computer Software Engineer
MBMG | Montana Tech
1300 W Park St, NRB 329 A | Butte, MT 59701

**Comment by FuhuXia** [comment]
@lukejbuckley 
That is correct. Any time if there is a production.ini.rpmnew file shows up after rpm update, you need to re-do the (1) and (2).  Step(3) need to be done once. And if you are coming from rpm version 300 or before, you need to do the manual database changes as listed.

**Comment by lukejbuckley** [comment]
@fuhuxia @ccaudill

Following is the contents of my global.xml (/var/lib/tomcat6/webapps/geoserver/data) file. There is no proxyBaseUrl element with a value of 127.0.0.1 to replace. Do I need to add it somewhere? Or ignore the step?

<global>
  <contact>
    <addressCity>Alexandria</addressCity>
    <addressCountry>Egypt</addressCountry>
    <addressType>Work</addressType>
    <contactEmail>claudius.ptolomaeus@gmail.com</contactEmail>
    <contactOrganization>The ancient geographes INC</contactOrganization>
    <contactPerson>Claudius Ptolomaeus</contactPerson>
    <contactPosition>Chief geographer</contactPosition>
  </contact>
  <jai>
    <allowInterpolation>false</allowInterpolation>
    <recycling>false</recycling>
    <tilePriority>5</tilePriority>
    <tileThreads>7</tileThreads>
    <memoryCapacity>0.5</memoryCapacity>
    <memoryThreshold>0.75</memoryThreshold>
    <imageIOCache>false</imageIOCache>
    <pngAcceleration>true</pngAcceleration>
    <jpegAcceleration>true</jpegAcceleration>
    <allowNativeMosaic>false</allowNativeMosaic>
  </jai>
  <coverageAccess>
    <maxPoolSize>10</maxPoolSize>
    <corePoolSize>5</corePoolSize>
    <keepAliveTime>30000</keepAliveTime>
    <queueType>UNBOUNDED</queueType>
    <imageIOCacheThreshold>10240</imageIOCacheThreshold>
  </coverageAccess>
  <charset>UTF-8</charset>
  <numDecimals>8</numDecimals>
  <onlineResource>http://geoserver.org</onlineResource>
  <verbose>false</verbose>
  <verboseExceptions>false</verboseExceptions>
  <updateSequence>78</updateSequence>
  <featureTypeCacheSize>0</featureTypeCacheSize>
  <globalServices>true</globalServices>
  <xmlPostRequestLogBufferSize>1024</xmlPostRequestLogBufferSize>
</global>

**Comment by FuhuXia** [comment]
Thanks for the catch. we have updated the global.xml file after rpm 300 but i missed the step in instrucitons for 200 and previous. 
```
      service tomcat6 stop
      chown tomcat:tomcat /var/tmp/geoserver.global.xml
      cp -f /var/tmp/geoserver.global.xml /var/lib/tomcat6/webapps/geoserver/data/global.xml
```
make changes to proxyBaseUrl per instruction, then
```
      service tomcat6 start
```
I will update the Readme file later.

**Comment by lukejbuckley** [comment]
@fuhuxiz @ccaudill

That part worked.

I still get the following when I try to start the db statements

[root@MBMGGIN tmp]# sudo -u postgres createdb -O ckan_default pycsw -E utf-8
createdb: database creation failed: ERROR:  database "pycsw" already exists

**Comment by FuhuXia** [comment]
@lukejbuckley 
It is ok, not sure which version you are updating from, but the pycsw table has be created by rpm or some manual process. Anyway, just move on the finish all the commands. It does not hurt anything to run those commands on existing database.

**Comment by lukejbuckley** [comment]
@ccaudill

All the steps are finished on my end. Test away.

**Comment by ccaudill** [comment]
Thanks @lukejbuckley @FuhuXia I'm testing a harvest from the MT node this morning.

**Comment by ccaudill** [comment]
@FuhuXia Latest attempt to harvest.... For the last half hour or so, the message in the UI http://159.87.39.5/harvest/admin/montana-geological-survey-ngds-node has said "Running" with nothing being harvested in. Here is the harvester log:

[root@localhost ~]# tail -n 50 /var/log/harvester_run.log
2015-03-12 07:30:20,129 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-03-12 07:30:20,133 DEBUG [ckanext.harvest.model] Harvest tables already exist
2015-03-12 07:30:20,222 INFO  [ckanext.harvest.logic.action.update] Harvest job run: {}
2015-03-12 07:30:20,297 INFO  [ckanext.harvest.logic.action.update] No new harvest jobs.

Traceback (most recent call last):
  File "/usr/bin/ckan", line 59, in <module>
    load_entry_point('PasteScript', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 122, in command
    self.run_harvester()
  File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 287, in run_harvester
    jobs = get_action('harvest_jobs_run')(context,{})
  File "/usr/lib/ckan/src/ckan/ckan/logic/__init__.py", line 419, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/logic/action/update.py", line 338, in harvest_jobs_run
    raise Exception('There are no new harvesting jobs')
Exception: There are no new harvesting jobs
2015-03-12 07:45:15,698 INFO  [ckanext.facets.helpers] Metadata plugin custom facets loaded
2015-03-12 07:45:15,703 DEBUG [ckanext.ngds.sysadmin.model.db] Sysadmin configuration table already exists
2015-03-12 07:45:19,709 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2015-03-12 07:45:19,730 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2015-03-12 07:45:19,746 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-03-12 07:45:19,749 DEBUG [ckanext.harvest.model] Harvest tables already exist
2015-03-12 07:45:19,835 INFO  [ckanext.harvest.logic.action.update] Harvest job run: {}
2015-03-12 07:45:19,906 INFO  [ckanext.harvest.logic.action.update] No new harvest jobs.

Traceback (most recent call last):
  File "/usr/bin/ckan", line 59, in <module>
    load_entry_point('PasteScript', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 122, in command
    self.run_harvester()
  File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 287, in run_harvester
    jobs = get_action('harvest_jobs_run')(context,{})
  File "/usr/lib/ckan/src/ckan/ckan/logic/__init__.py", line 419, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/logic/action/update.py", line 338, in harvest_jobs_run
    raise Exception('There are no new harvesting jobs')
Exception: There are no new harvesting jobs

**Comment by FuhuXia** [comment]
the log looks fine. please post the other two logs to see if there is any error.
`tail -n 20 /var/log/gather-consumer.log`
`tail -n 20 /var/log/fetch-consumer.log`

I also tried on my local. It shows http://mbmggin.mtech.edu/csw contains no record.

**Comment by ccaudill** [comment]
[root@localhost ~]# tail -n 20 /var/log/gather-consumer.log
    params)
  File "/usr/lib/ckan/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1584, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/ckan/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1698, in _execute_context
    context)
  File "/usr/lib/ckan/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1691, in _execute_context
    context)
  File "/usr/lib/ckan/lib/python2.6/site-packages/sqlalchemy/engine/default.py", line 331, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (OperationalError) server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
 'SELECT harvest_job.id AS harvest_job_id, harvest_job.created AS harvest_job_created, harvest_job.gather_started AS harvest_job_gather_started, harvest_job.gather_finished AS harvest_job_gather_finished, harvest_job.finished AS harvest_job_finished, harvest_job.source_id AS harvest_job_source_id, harvest_job.status AS harvest_job_status \nFROM harvest_job \nWHERE harvest_job.id = %(id_1)s \n LIMIT %(param_1)s' {'id_1': u'fa6603ef-61ab-43f3-89e2-5eb49e5e1bcf', 'param_1': 1}
2015-03-12 07:15:30,728 INFO  [ckanext.facets.helpers] Metadata plugin custom facets loaded
2015-03-12 07:15:30,737 DEBUG [ckanext.ngds.sysadmin.model.db] Sysadmin configuration table already exists
2015-03-12 07:15:33,430 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2015-03-12 07:15:33,463 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2015-03-12 07:15:33,483 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-03-12 07:15:33,489 DEBUG [ckanext.harvest.model] Harvest tables already exist
2015-03-12 07:15:33,605 DEBUG [ckanext.harvest.queue] Gather queue consumer registered

**Comment by ccaudill** [comment]
[root@localhost ~]# tail -n 20 /var/log/fetch-consumer.log
2015-02-18 15:21:28,049 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2015-02-18 15:21:28,074 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2015-02-18 15:21:28,092 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-02-18 15:21:28,095 DEBUG [ckanext.harvest.model] Harvest tables already exist
2015-02-18 15:21:28,206 DEBUG [ckanext.harvest.queue] Fetch queue consumer registered
2015-02-18 15:21:28,897 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2015-02-18 15:21:28,929 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2015-02-18 15:21:28,946 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-02-18 15:21:28,950 DEBUG [ckanext.harvest.model] Harvest tables already exist
2015-02-18 15:21:29,052 DEBUG [ckanext.harvest.queue] Fetch queue consumer registered
2015-02-18 15:21:29,834 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2015-02-18 15:21:29,857 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2015-02-18 15:21:29,874 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-02-18 15:21:29,878 DEBUG [ckanext.harvest.model] Harvest tables already exist
2015-02-18 15:21:29,982 DEBUG [ckanext.harvest.queue] Fetch queue consumer registered
2015-02-18 15:21:33,898 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
2015-02-18 15:21:33,924 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
2015-02-18 15:21:33,943 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2015-02-18 15:21:33,948 DEBUG [ckanext.harvest.model] Harvest tables already exist
2015-02-18 15:21:34,058 DEBUG [ckanext.harvest.queue] Fetch queue consumer registered

**Comment by FuhuXia** [comment]
If the harvest job status still stays at running, you can clear and re-harvest the job. It does not hurt to run a command `supervisorctl restart all` before doing that.

**Comment by ccaudill** [comment]
So the error message after it ran was "No records received from the CSW server".
What do you think is going on here?  There's clearly records (44) in this CKAN instance: http://mbmggin.mtech.edu/dataset

But it is strange that
http://mbmggin.mtech.edu/csw?request=GetRecords&service=CSW&version=2.0.2
Doesn't give you the response you'd expect, which is this:
http://catalog.stategeothermaldata.org/geoportal/csw?request=GetRecords&service=CSW&version=2.0.2
telling you the number of total records from the CSW endpoint.

Does this point to a problem with the pyCSW?

**Comment by ccaudill** [comment]
@FuhuXia pyCSW will harvest in everything, correct? Resources which were published on the node as well as those which were harvested into that node?  It seems that harvests are working, but we can't seem to get a CKAN-CKAN harvest working. MT node only has harvested resources, and no published resources.

**Comment by ccaudill** [comment]
@FuhuXia Could you tell us what the DB, username, and password would be for Postgres the install in the rpm? We'd like to take a look and see if the data is getting populated correctly there, and if there is something lost between Postgres and CKAN's data store.

**Comment by FuhuXia** [comment]
@ccaudill 
You can see there are two commands in the pycsw cron jobs.
https://github.com/ngds/install-and-run/blob/master/rpm_install/etc/cron.d/ckan-pycsw#L2
the first `ckan-pycsw load` command will load any harvested data. The second `datastore-pycsw load` command will load local data that fit in this criteria. 
https://github.com/ngds/ckanext-datastorecsw/blob/master/bin/datastore_pycsw.py#L74
If a published data does not appear in the query result, it wont get into csw records.

All DB info is in `/etc/ckan/production.ini` file
https://github.com/ngds/install-and-run/blob/master/rpm_install/etc/ckan/production.ini#L48

**Comment by FuhuXia** [comment]
@ccaudill 
For the the MT server published dataset no going to csw issue, can you run the command and provide the output?
`/usr/lib/ckan/bin/paster --plugin=ckanext-spatial ckan-pycsw load -p /etc/ckan/pycsw.cfg && /usr/lib/ckan/bin/paster --plugin=ckanext-datastorecsw datastore-pycsw load -p /etc/ckan/pycsw.cfg`

**Comment by FuhuXia** [comment]
@smrazgs 
Let us split the command into two commands and run them one after the other. Please post results, you can trim off repetitive ones, if any.

`/usr/lib/ckan/bin/paster --plugin=ckanext-spatial ckan-pycsw load -p /etc/ckan/pycsw.cfg`

`/usr/lib/ckan/bin/paster --plugin=ckanext-datastorecsw datastore-pycsw load -p /etc/ckan/pycsw.cfg`

**Comment by smrazgs** [comment]
I ran the commands on 159.87.39.5
First one seemed to work OK, lots of inserts with GUIDS, and fails on duplicate GUIDS

Second one gagged, here's the beginning of the console output:

[root@localhost ~]# /usr/lib/ckan/bin/paster --plugin=ckanext-datastorecsw datastore-pycsw load -p /etc/ckan/pycsw.cfg

-bash: syntax error near unexpected token `command,'

[root@localhost ~]#   File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 143, in invoke
-bash: File: command not found

[root@localhost ~]#     exit_code = runner.run(args)
-bash: syntax error near unexpected token `('

[root@localhost ~]#   File "/usr/lib/ckan/lib/python2.6/site-packages/paste/script/command.py", line 238, in run

rest of it is -bash errors mostly--like its trying to run a script that's not a script?  I can send the console dump if that would be usefrul.

**Comment by smrazgs** [comment]
on 159.87.39.4:

login as: root
root@159.87.39.4's password:
Last login: Thu Feb 26 14:22:35 2015 from 10.208.1.175
[root@localhost ~]# /usr/lib/ckan/bin/paster --plugin=ckanext-spatial ckan-pycsw load -p /etc/ckan/pycsw.cfg
/usr/lib/ckan/lib/python2.6/site-packages/sqlalchemy/engine/reflection.py:47: SAWarning: Did not recognize type 'tsvector' of column 'anytext_tsvector'
  ret = fn(self, con, *args, **kw)
/usr/lib/ckan/lib/python2.6/site-packages/sqlalchemy/engine/reflection.py:47: SAWarning: Did not recognize type 'geometry' of column 'wkb_geometry'
  ret = fn(self, con, *args, **kw)
Started gathering CKAN datasets identifiers: 2015-03-17 13:05:38.919103
Starting new HTTP connection (1): localhost
Starting new HTTP connection (1): localhost
Gather finished (38 datasets): 2015-03-17 13:05:39.031257
Starting new HTTP connection (1): localhost
Inserted 15e331cc-d6fa-4986-b339-4beec0bb996b
Starting new HTTP connection (1): localhost
Inserted d2141d76-a7b3-4e88-8127-3e8c2509906f
Starting new HTTP connection (1): localhost
Inserted 7286ad2a-e9df-4f1f-9cb4-b3c55c3c2a67
Starting new HTTP connection (1): localhost

...lots of the same kind, different guids...

Starting new HTTP connection (1): localhost
Inserted d66f2c4e-8746-47a8-bb34-4f07e1e52eaa
Starting new HTTP connection (1): localhost
Inserted 178c6d5b-568a-4988-8bf1-da52caae24ff
[root@localhost ~]#
[root@localhost ~]#
[root@localhost ~]# /usr/lib/ckan/bin/paster --plugin=ckanext-datastorecsw datastore-pycsw load -p /etc/ckan/pycsw.cfg
/usr/lib/ckan/lib/python2.6/site-packages/sqlalchemy/engine/reflection.py:47: SAWarning: Did not recognize type 'tsvector' of column 'anytext_tsvector'
  ret = fn(self, con, *args, **kw)
/usr/lib/ckan/lib/python2.6/site-packages/sqlalchemy/engine/reflection.py:47: SAWarning: Did not recognize type 'geometry' of column 'wkb_geometry'
  ret = fn(self, con, *args, **kw)
Started gathering CKAN datasets identifiers: 2015-03-17 13:06:00.479655
Starting new HTTP connection (1): localhost
..5 more the same...
Starting new HTTP connection (1): localhost
Starting new HTTP connection (1): localhost
Gather finished (3 datasets): 2015-03-17 13:06:00.896071
Starting new HTTP connection (1): localhost
Inserted ef0f103f-4b3a-4421-8804-98d34e61c93e
Starting new HTTP connection (1): localhost
Inserted 9e7d925b-0a6b-49bd-b06b-380da3c75449
Starting new HTTP connection (1): localhost
Inserted 52378851-ea66-40d9-9388-9aa912e308ce
[root@localhost ~]#

**Comment by smrazgs** [comment]
this wfs request now works:
http://159.87.39.4/csw?request=GetRecords&version=2.0.2&service=CSW&typeNames=csw:Record&resultType=results&outputFormat=application/xml&ElementSetName=brief

**Comment by ccaudill** [comment]
It looks like Postgres is not listening...

[root@localhost ~]# netstat -antup | grep 5432
tcp        0      0 0.0.0.0:5432                0.0.0.0:*                   LISTEN      12579/postmaster
tcp      111      0 127.0.0.1:56744             127.0.0.1:5432              CLOSE_WAIT  2761/demo
tcp      111      0 127.0.0.1:52643             127.0.0.1:5432              CLOSE_WAIT  1412/python
tcp      111      0 127.0.0.1:52581             127.0.0.1:5432              CLOSE_WAIT  1404/python
tcp      111      0 127.0.0.1:52618             127.0.0.1:5432              CLOSE_WAIT  1406/python
tcp      111      0 127.0.0.1:52594             127.0.0.1:5432              CLOSE_WAIT  1405/python
tcp      111      0 127.0.0.1:52628             127.0.0.1:5432              CLOSE_WAIT  1408/python
tcp      111      0 127.0.0.1:52579             127.0.0.1:5432              CLOSE_WAIT  1404/python
tcp      111      0 127.0.0.1:52654             127.0.0.1:5432              CLOSE_WAIT  1409/python
tcp      111      0 127.0.0.1:52629             127.0.0.1:5432              CLOSE_WAIT  1408/python
tcp      111      0 127.0.0.1:52913             127.0.0.1:5432              CLOSE_WAIT  2761/demo
tcp      111      0 127.0.0.1:52537             127.0.0.1:5432              CLOSE_WAIT  1411/python
tcp      111      0 127.0.0.1:52616             127.0.0.1:5432              CLOSE_WAIT  1406/python
tcp      111      0 127.0.0.1:52663             127.0.0.1:5432              CLOSE_WAIT  1407/python
tcp      111      0 127.0.0.1:52542             127.0.0.1:5432              CLOSE_WAIT  1404/python
tcp      111      0 127.0.0.1:52660             127.0.0.1:5432              CLOSE_WAIT  1407/python
tcp      111      0 127.0.0.1:52541             127.0.0.1:5432              CLOSE_WAIT  1412/python
tcp      111      0 127.0.0.1:52610             127.0.0.1:5432              CLOSE_WAIT  1410/python
tcp      111      0 127.0.0.1:52608             127.0.0.1:5432              CLOSE_WAIT  1410/python
tcp      111      0 127.0.0.1:52578             127.0.0.1:5432              CLOSE_WAIT  1404/python
tcp      111      0 127.0.0.1:52611             127.0.0.1:5432              CLOSE_WAIT  1410/python
tcp      111      0 127.0.0.1:52630             127.0.0.1:5432              CLOSE_WAIT  1408/python
tcp      111      0 127.0.0.1:52631             127.0.0.1:5432              CLOSE_WAIT  1408/python
tcp      111      0 127.0.0.1:52857             127.0.0.1:5432              CLOSE_WAIT  2760/demo
tcp      111      0 127.0.0.1:52539             127.0.0.1:5432              CLOSE_WAIT  1405/python
tcp      111      0 127.0.0.1:52595             127.0.0.1:5432              CLOSE_WAIT  1405/python
tcp      111      0 127.0.0.1:52912             127.0.0.1:5432              CLOSE_WAIT  2761/demo
tcp        0      0 127.0.0.1:5432              127.0.0.1:56759             ESTABLISHED 12688/postgres
tcp      111      0 127.0.0.1:52587             127.0.0.1:5432              CLOSE_WAIT  1411/python
tcp      111      0 127.0.0.1:52540             127.0.0.1:5432              CLOSE_WAIT  1409/python
tcp      111      0 127.0.0.1:53382             127.0.0.1:5432              CLOSE_WAIT  2760/demo
tcp      111      0 127.0.0.1:52662             127.0.0.1:5432              CLOSE_WAIT  1407/python
tcp      111      0 127.0.0.1:52859             127.0.0.1:5432              CLOSE_WAIT  2760/demo
tcp      111      0 127.0.0.1:52858             127.0.0.1:5432              CLOSE_WAIT  2760/demo
tcp      111      0 127.0.0.1:52545             127.0.0.1:5432              CLOSE_WAIT  1407/python
tcp      111      0 127.0.0.1:52580             127.0.0.1:5432              CLOSE_WAIT  1404/python
tcp      111      0 127.0.0.1:52653             127.0.0.1:5432              CLOSE_WAIT  1409/python
tcp      111      0 127.0.0.1:52620             127.0.0.1:5432              CLOSE_WAIT  1406/python
tcp        0      0 127.0.0.1:56759             127.0.0.1:5432              ESTABLISHED 2760/demo
tcp      111      0 127.0.0.1:52640             127.0.0.1:5432              CLOSE_WAIT  1412/python
tcp      111      0 127.0.0.1:52538             127.0.0.1:5432              CLOSE_WAIT  1410/python
tcp      111      0 127.0.0.1:52596             127.0.0.1:5432              CLOSE_WAIT  1405/python
tcp      111      0 127.0.0.1:52544             127.0.0.1:5432              CLOSE_WAIT  1408/python
tcp      111      0 127.0.0.1:52911             127.0.0.1:5432              CLOSE_WAIT  2761/demo
tcp      111      0 127.0.0.1:52609             127.0.0.1:5432              CLOSE_WAIT  1410/python
tcp      111      0 127.0.0.1:52589             127.0.0.1:5432              CLOSE_WAIT  1411/python
tcp      111      0 127.0.0.1:52652             127.0.0.1:5432              CLOSE_WAIT  1409/python
tcp      111      0 127.0.0.1:52617             127.0.0.1:5432              CLOSE_WAIT  1406/python
tcp      111      0 127.0.0.1:52641             127.0.0.1:5432              CLOSE_WAIT  1412/python
tcp      111      0 127.0.0.1:52543             127.0.0.1:5432              CLOSE_WAIT  1406/python
tcp      111      0 127.0.0.1:52586             127.0.0.1:5432              CLOSE_WAIT  1411/python
tcp      111      0 127.0.0.1:52655             127.0.0.1:5432              CLOSE_WAIT  1409/python
tcp      111      0 127.0.0.1:53381             127.0.0.1:5432              CLOSE_WAIT  2760/demo
tcp      111      0 127.0.0.1:52661             127.0.0.1:5432              CLOSE_WAIT  1407/python
tcp      111      0 127.0.0.1:52642             127.0.0.1:5432              CLOSE_WAIT  1412/python
tcp      111      0 127.0.0.1:52597             127.0.0.1:5432              CLOSE_WAIT  1405/python
tcp      111      0 127.0.0.1:52588             127.0.0.1:5432              CLOSE_WAIT  1411/python
tcp        0      0 :::5432                     :::*                        LISTEN      12579/postmaster

**Comment by ccaudill** [comment]
FYI - I had to run the following command for Postgres to allow a connection and to not be rejected to traffic:
iptables -I INPUT 1 -p tcp --dport 5432 -j ACCEPT
(ran it in 10.208.3.122/159.87.39.4)

**Comment by ccaudill** [comment]
You actually have to run these commands so that it sticks:

iptables -I INPUT 1 -p tcp --dport 5432 -j ACCEPT
service iptables save
service iptables restart

This should be in the rpm??

**Comment by ccaudill** [comment]
@FuhuXia @smrazgs @dan-olaru-reisys It FINALLY harvested in!!!
http://10.208.3.104/harvest/azgs-ginstack-test-harvest/job/14da6a65-257a-428b-ac64-feae305125c1
 The fact that the CentOS firewall is set to automatically stop traffic to/from Postgres in a GINstack build seems to have been the problem. 

@lukejbuckley - Might you have time to try and run these commands, then we'll try a harvest again from your node?

iptables -I INPUT 1 -p tcp --dport 5432 -j ACCEPT
service iptables save
service iptables restart

Then, you have to get into the /var/lib/pgsql/9.1/data/postgresql.conf and make it as such:

# - Connection Settings -
listen_addresses = '*'		# what IP address(es) to listen on;
					# comma-separated list of addresses;
					# defaults to 'localhost', '*' = all
					# (change requires restart)
port = 5432				# (change requires restart)

We also had to edit the  /var/lib/pgsql/9.1/data/pg_hba.conf but hopefully you won't have to do that too.

**Comment by lukejbuckley** [comment]
@ccaudill I ran the commands and restarted the machine.

**Comment by ccaudill** [comment]
@FuhuXia 
Okay, since Luke has run those commands, and from
http://mbmggin.mtech.edu/csw?request=GetCapabilities&Service=CSW&Version=2.0.2
I'm still getting the error message, "Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?"
It is clear that in the rpm for a GINstack, the postgresql.conf and the pg_hba.conf  have to be edited to allow traffic. That seems like it's the answer to solving this and should be in a new build of the rpm. Can you please confirm?

**Comment by FuhuXia** [comment]
@ccaudill 
For the port 5432 firewall rule change, do you have to make the change to all ngds servers, or just one particular server? If I set up some fresh instances on amazon with the rpm installed, can you replicate the issue on the fresh instances?

The reason I want to check it this way is that we definitely don't want to enable this firewall rule on any public ngds server. We are using a default postgres db user credential. If the port is open, anyone is going to have full access to ngds database. In the rpm script, we only have port 80 open, as coded in here https://github.com/ngds/install-and-run/blob/master/rpm_install/tmp/after_rpm.sh#L203.

**Comment by ccaudill** [comment]
Thanks @FuhuXia The port has to be open to 5432 for the harvest to work, and that is not how it comes in the install. Sure, if you set up some fresh ones, I can recreate this. It is simply about editing those two files to allow traffic on 5432 and to allow anyone to access the data. This is what we want - it is the idea that public access is allowable to these servers - anyone should be able to harvest from them without permission and without editing any files.

**Comment by FuhuXia** [comment]
Harvesting is done via web api at the port 80. The local communication between ckan and postgresql does not need firewall rule change on port 5432. Ok, I will launch an fresh ngds server and we can work on that one to solve the mystery PostgreSQL port issue.

**Comment by ccaudill** [comment]
We did this test systematically, and all of those things had to happen before a harvest was successful. It will be interesting with a fresh server - let me know when I can help.

**Comment by FuhuXia** [comment]
@ccaudill 
Ok, this instance was started with centos 6.4 with rpm 303 a few weeks ago. I just updated it to rpm 307. It can harvest datasets in, and can be harvested out. No special firewall about port 5432. Can you go through the site and point out which part is not functioning as expected? Let me know if you need ckan or ssh access.
http://184.73.219.216/dataset

**Comment by ccaudill** [comment]
I can see that I actually get a response from http://184.73.219.216/csw?request=GetCapabilities&Service=CSW&Version=2.0.2 so it seems to be working from all your installs, but not ours or our partners installs.  Should we ask (as soon as the issue https://github.com/ngds/ckanext-geoserver/issues/7 is resolved) to completely empty their server and install this new build?  Since I do get a response from the CSW from your new build and do not from our partners at MT, I'm guessing the harvest will work fine from yours - I'm testing that now.

**Comment by FuhuXia** [comment]
@ccaudill 
If we can find an easy and reliable way to replicate the issue yuou are experiencing on a freshly installed instance, it makes much easier for me to fix it. This way you don't have to wipe your existing servers. If not, then starting new might make more sense.

**Comment by ccaudill** [comment]
thanks @FuhuXia, we'll try that!

**Comment by ccaudill** [comment]
@FuhuXia  I wonder if you could provide me the postgresql.conf and the pg_hba.conf files from your fresh install, just so I can compare with what we had on a fresh install?

**Comment by smrazgs** [comment]
@ccaudill @FuhuXia  this issue thread is pretty far from the topic line above. Please start new issues when discussing a different problem-- that will make it easier to find things in the issue tracker. You could reference the beginning of the discussion in another thread for situations like this where a problem evolves.

**Comment by ccaudill** [comment]
@FuhuXia Can you comment on Steve's from 3/17 above? It seems that those commands got the CSW working. Are those something that can do into the harvest process?

Comments after that regarding Postgres and harvesting can be carried on at https://github.com/ngds/install-and-run/issues/25 as they don't really have bearing on just whether or not the pyCSW is being properly populated. ... Sorry for going so off-topic there!

**Comment by smrazgs** [comment]
pycsw is working on the current rpm install e.g.
http://uat-ngds.reisys.com/csw?request=GetRecords&version=2.0.2&service=CSW&typeNames=csw:Record&resultType=results&outputFormat=application/xml&ElementSetName=brief

The issue is not the pycsw installation but the firewall and security issues in the OS. Close this issue, and see #25

**Comment by ccaudill** [comment]
http://final.geothermaldata.org/harvest/admin/geological-survey-of-alabama-gin-stack 
@dan-olaru-reisys This test harvest has been RUnning for an hour and a half and nothing has harvested. Might you have any suggestions? This is the important test before we can move forward with a v2

**Comment by smrazgs** [comment]
Christy-- there are 10 records showing as harvested fro this source now, consistent with what I get with a csw request:
http://ginstack.gsa.state.al.us/csw?request=GetRecords&version=2.0.2&service=CSW&typeNames=csw:Record&outputSchema=http://www.isotc211.org/2005/gmd&resultType=results&outputFormat=application/xml&ElementSetName=full&maxRecords=20

I think its working

**Comment by ccaudill** [comment]
WOOHOO!  I'm not sure why it took so long, but it is working!
